[workspace]
resolver = "3"
members = ["client", "server", "utils"]

[workspace.dependencies]
async-std = { version = "1.13.1", features = ["attributes"] }
crossterm = "0.29.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tui = "0.19.0"
